# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 571af1bf41f5b88d7d0fc04f37b309719285d8777dfffdc9abd65c665f388b53bd4f09ac53db35d22bf5f1be69f882d6b7e05c81da9d28bac64936effea1182d

test:
  secret_key_base: aa71cfc59e44beb67bad5e697495bfadc340f311ff4b07eb12fa33364761cb6aa7e6e0580e1f46dc4c7d7d250603fa11f30c330166ffd58d34ac00cef3e0ade0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
